interfaces:
  3/1: 
    type: Serial
    ip_v4: 172.16.1.2 255.255.255.252
    ip_v6: 2001:DB8:ACAD:1::2/64
    clock_rate: 128000
    description: connected_to_R1
  3/2: 
    type: Serial
    ip_v4: 172.16.2.2 255.255.255.252
    ip_v6: 2001:DB8:ACAD:2::2/64
    clock_rate: 128000
    description: connected_to_R3
  1/0:
    type: FastEthernet
    ip_v4: 209.165.200.233 255.255.255.248
    ip_v6: 2001:DB8:ACAD:A::1/64
    description: connected_to_Internet
  0:
    type: Loopback
    ip_v4: 10.10.10.10 255.255.255.255
    description: connected_to_Webserver

routes:
  3/1:
    type: Serial
    ip_v4: 0.0.0.0 0.0.0.0
    ip_v6: ::/0    

rip_networks:
  - 172.16.1.0
  - 172.16.2.0
  - 10.10.10.10
  - 209.165.200.232

passive_ifaces:
  - Loopback0

is_server: true

static_nat:
  webserver:
    in_lo_addr: 10.10.10.10
    in_gl_addr: 209.165.200.237
    in_iface: Loopback0
    out_iface: FastEthernet1/0

dynamic_nat:
  name: INTERNET
  start: 209.165.200.234
  end: 209.165.200.236
  mask: 255.255.255.248
  acl:
    number: 1
    permitted:
      - 192.168.21.0 0.0.0.255
      - 192.168.23.0 0.0.0.255
  in_int: Serial3/0
  out_int: FastEthernet1/0

# extended_acls:
#   ADMIN-MGT:
#     allowed_host_map:
#       - host 172.16.1.1 host 172.16.1.2
#       - host 192.168.122.1 host 172.16.1.2
#     allowed_tcp:
#       - 22
#       - 23  
#   applied_interface: line vty 0 4
#   applied_interface_io: access-class MGT in

management_acl:
  name: ADMIN-MGT
  allowed_host_map: host 172.16.1.1 any
  admin: host 192.168.122.1 any