interfaces:
  3/2: 
    type: Serial
    ip_v4: 172.16.2.1 255.255.255.252
    ip_v6: 2001:DB8:ACAD:2::1/64
    clock_rate: 128000
    description: connected_to_R2
  4:
    type: Loopback
    ip_v4: 192.16.4.1 255.255.255.0
    description: Loopback 4
  5:
    type: Loopback
    ip_v4: 192.16.5.1 255.255.255.0
    description: Loopback 5
  6:
    type: Loopback
    ip_v4: 192.16.6.1 255.255.255.0
    description: Loopback 6
  7:
    type: Loopback
    ip_v4: 192.16.7.1 255.255.255.0
    description: Loopback 7

routes:
  3/2:
    type: Serial
    ip_v4: 0.0.0.0 0.0.0.0
    ip_v6: ::/0  

rip_config:
  - 172.16.2.0
  - 192.168.4.0
  - 192.168.5.0
  - 192.168.6.0

passive_ifaces:
  - Loopback4
  - Loopback5
  - Loopback6
