ansible_ssh_user: cisco
ansible_ssh_pass: cisco
ansible_become: yes
ansible_become_pass: cisco
ansible_network_os: ios
ansible_connection: network_cli
ansible_become_method: enable
ansible_ssh_common_args: -oKexAlgorithms=+diffie-hellman-group1-sha1

motd_banner: Unauthorized Access is Prohibited!