interfaces:
 R1:
  3/1: 
    type: Serial
    ip_v4: 172.16.1.1 255.255.255.252
    ip_v6: 2001:DB8:ACAD:1::1/64
    clock_rate: 128000
    description: connected_to_R2
 R2:
  3/1: 
    type: Serial
    ip_v4: 172.16.1.2 255.255.255.252
    ip_v6: 2001:DB8:ACAD:1::2/64
    clock_rate: 128000
    description: connected_to_R1
  3/2: 
    type: Serial
    ip_v4: 172.16.2.2 255.255.255.252
    ip_v6: 2001:DB8:ACAD:2::2/64
    clock_rate: 128000
    description: connected_to_R3
 R3:
  3/2: 
    type: Serial
    ip_v4: 172.16.2.1 255.255.255.252
    ip_v6: 2001:DB8:ACAD:2::1/64
    clock_rate: 128000
    description: connected_to_R2

routes:
 R1:
  3/1:
    type: Serial
    ip_v4: 0.0.0.0 0.0.0.0
    ip_v6: ::/0

networks:
 R1:
  3/1: 
   type: Serial
   network: 172.16.1.0 255.255.255.252

