- name: Install MySQL packages
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  become: yes

- name: Install dependencies for python mysqlclient
  apt: name={{ item }} state=latest
  with_items:
    - python3-pip
    - python-dev
    - libmysqlclient-dev
  become: yes

- name: Install mysqlclient via pip
  pip: name=mysqlclient
  become: yes

- name: Create a new database for Wordpress
  mysql_db:
    name: wordpressDb
    state: present
  become: yes

- name: Create new user with all privileges
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_pass }}"
    priv: 'wordpressDb.*:ALL'
    state: present

  become: yes
