---
- name: Setup Routers
  hosts: routers
  gather_facts: false
  tasks:
    - include_tasks: common_conf.yml

    - name: no ip http secure-server
      ios_config:
        lines:
          - no ip http secure-server

    - name: configure ospf
      ios_config:
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
          - network 10.0.2.0 0.0.0.3 area 0
          - network 10.0.3.0 0.0.0.3 area 0
          - network 192.168.122.0 0.0.0.255 area 0
        parents: router ospf 1

    - name: show ospf neig
      ios_command:
        commands:
          show ip ospf neighbor
      register: my_output

    - debug: var=my_output
