- name: install LAMP stack on server
  hosts: servers
  become: yes

  tasks:
    - name: Install Apache
      apt: name={{ item }} state=present
      with_items:
        - apache2
        - php
        - libapache2-mod-php
        - php-mcrypt
        - php-mysql

    - name: copy index.php to /var/www/html
      copy:
        src: ../files/index.php
        dest: /var/www/html/index.php
    
    - name: Make sure we can use htpasswd module
      apt: name=python3-passlib state=present
      when: ansible_python.version.major == 2

    - name: Make sure we can use htpasswd module
      apt: name=python3-passlib state=present
      when: ansible_python.version.major != 2

    - name: edit apache password file
      htpasswd:
        path: /etc/apache2/passwdfile
        create: yes
        name: "{{ http_user }}"
        password: "{{ http_password }}"
        owner: root
        group: www-data
        mode: 0640
        state: present

    - name: setup basic authentication for /var/www/html directory content
      copy:
        content: |
          <VirtualHost *:80>
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/html
            ErrorLog ${APACHE_LOG_DIR}/error.log
            CustomLog ${APACHE_LOG_DIR}/access.log combined
            <Directory "/var/www/html">
              AuthType Basic
              AuthName "Restricted Content"
              AuthUserFile /etc/apache2/passwdfile
              Require valid-user
            </Directory>
          </VirtualHost>
        dest: /etc/apache2/sites-available/000-default.conf

    - name: Create directory for WP in /var/www/html/
      file:
        state: directory
        path: /var/www/html/wp

    - name: Download Wordpress archive, then unarchive
      unarchive:
        src: http://wordpress.org/latest.tar.gz
        dest: /var/www/html/wp
        remote_src: yes


    - name: restart apache
      service:
        name: apache2
        state: restarted
